.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "YPKG" "1" "July 2023" ""
.SH "NAME"
\fBypkg\fR \- Build Solus ypkg files
.SH "SYNOPSIS"
\fBypkg <flags> [package\.yml]\fR
.SH "DESCRIPTION"
\fBypkg\fR is the main entry point into \fBpackage\.yml(5)\fR program\. It is a stub that will first call out to \fBypkg\-install\-deps(1)\fR before passing off to \fBypkg\-build(1)\fR\. See those manpages for more details\.
.P
Note that you should not use \fBypkg(1)\fR directly unless completely unavoidable\. Instead, you should be using \fBsolbuild(1)\fR for isolated build environments\.
.SH "OPTIONS"
The following options are applicable to \fBypkg(1)\fR\.
.IP "\[ci]" 4
\fB\-h\fR, \fB\-\-help\fR
.IP
Print the command line options for \fBypkg(1)\fR and exit\.
.IP "\[ci]" 4
\fB\-v\fR, \fB\-\-version\fR
.IP
Print the \fBypkg(1)\fR version and exit\.
.IP "\[ci]" 4
\fB\-n\fR, \fB\-\-no\-colors\fR
.IP
Disable text colourisation in the output from \fBypkg\fR and all child processes\.
.IP "\[ci]" 4
\fB\-D\fR, \fB\-\-output\-dir\fR
.IP
Set the output directory for \fBypkg\-build(1)\fR
.IP "\[ci]" 4
\fB\-f\fR, \fB\-\-force\fR
.IP
Force the installation of package dependencies, which will bypass any prompting by ypkg\. The default behaviour is to prompt before installing packages\.
.IP "" 0
.SH "EXIT STATUS"
On success, 0 is returned\. A non\-zero return code signals a failure\.
.SH "COPYRIGHT"
.IP "\[ci]" 4
Copyright \(co 2016\-2020 Solus Project
.IP "" 0
.P
Released under the terms of the CC\-BY\-SA\-3\.0 license
.SH "SEE ALSO"
\fBsolbuild(1)\fR, \fBypkg\-install\-deps(1)\fR, \fBypkg\-build(1)\fR, \fBpackage\.yml(5)\fR
.IP "\[ci]" 4
https://github\.com/getsolus/ypkg
.IP "\[ci]" 4
https://getsol\.us/articles/packaging
.IP "" 0
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.IP "\[ci]" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.IP "" 0

