#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  ybump.py
#
#  Copyright 2015-2020 Solus Project
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
import sys
from ruamel.yaml import YAML


def usage(msg=None, ex=1):
    if msg:
        print(msg)
    else:
        print(("Usage: %s file.yml" % sys.argv[0]))
    sys.exit(ex)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        usage()

    with open(sys.argv[1]) as fp:
        lines = fp.readlines()
        fp.seek(0)
        yaml = YAML()
        data = yaml.load(fp)
    data['release'] += 1
    maxwidth = len(max(lines, key=len))
    try:
        with open(sys.argv[1], 'w') as fp:
            yaml.indent(mapping=4, sequence=4, offset=4)
            yaml.top_level_colon_align = True
            yaml.prefix_colon = ' '
            yaml.width = maxwidth
            yaml.dump(data, fp)
    except Exception as e:
        print("Error writing file, may need to reset it.")
        print(e)
        sys.exit(1)
